### ISSUE TITLE
no calendars displaying sometimes

### ISSUE THREAD

**Issue by davidmelvin** [JoshuaStorm/meetable#244]
I don't know how to replicate this issue when exactly it happens, but it happens fairly often (i know that's not helpful). 

It makes the calendars not display any events.

I'm pretty sure it happens on login or refresh but I can't get it to happen in my current Bert alert branch

```
Exception while invoking method 'getFullCalendarConsidered' Error: Not Found
I20170507-02:30:42.917(-4)?     at Object.Future.wait (/Users/david/.meteor/packages/meteor-tool/.1.4.3_2.1bvf0xf++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:449:15)
I20170507-02:30:42.918(-4)?     at packages/meteor.js:213:24
I20170507-02:30:42.918(-4)?     at [object Object].Meteor.methods.getFullCalendarEvents (server/googleCalendarAPI.js:135:24)
I20170507-02:30:42.919(-4)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1737:12)
I20170507-02:30:42.919(-4)?     at packages/ddp-server/livedata_server.js:1650:18
I20170507-02:30:42.919(-4)?     at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
I20170507-02:30:42.920(-4)?     at [object Object]._.extend.apply (packages/ddp-server/livedata_server.js:1649:45)
I20170507-02:30:42.920(-4)?     at [object Object]._.extend.call (packages/ddp-server/livedata_server.js:1592:17)
I20170507-02:30:42.921(-4)?     at [object Object].Meteor.methods.getFullCalendarConsidered (server/googleCalendarAPI.js:186:29)
I20170507-02:30:42.921(-4)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1737:12)
I20170507-02:30:42.922(-4)?     - - - - -
I20170507-02:30:42.922(-4)?     at Request._callback (/Users/david/Desktop/meetable/node_modules/google-auth-library/lib/transporters.js:85:15)
I20170507-02:30:42.922(-4)?     at Request.self.callback (/Users/david/Desktop/meetable/node_modules/request/request.js:188:22)
I20170507-02:30:42.923(-4)?     at emitTwo (events.js:87:13)
I20170507-02:30:42.923(-4)?     at Request.emit (events.js:172:7)
I20170507-02:30:42.923(-4)?     at Request.<anonymous> (/Users/david/Desktop/meetable/node_modules/request/request.js:1171:10)
I20170507-02:30:42.924(-4)?     at emitOne (events.js:77:13)
I20170507-02:30:42.924(-4)?     at Request.emit (events.js:169:7)
I20170507-02:30:42.925(-4)?     at IncomingMessage.<anonymous> (/Users/david/Desktop/meetable/node_modules/request/request.js:1091:12)
I20170507-02:30:42.925(-4)?     at IncomingMessage.g (events.js:260:16)
I20170507-02:30:42.925(-4)?     at emitNone (events.js:72:20)
I20170507-02:30:43.130(-4)? Exception while invoking method 'getFullCalendarConsidered' Error: Not Found
I20170507-02:30:43.130(-4)?     at Object.Future.wait (/Users/david/.meteor/packages/meteor-tool/.1.4.3_2.1bvf0xf++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:449:15)
I20170507-02:30:43.130(-4)?     at packages/meteor.js:213:24
I20170507-02:30:43.131(-4)?     at [object Object].Meteor.methods.getFullCalendarEvents (server/googleCalendarAPI.js:135:24)
I20170507-02:30:43.131(-4)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1737:12)
I20170507-02:30:43.131(-4)?     at packages/ddp-server/livedata_server.js:1650:18
I20170507-02:30:43.132(-4)?     at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
I20170507-02:30:43.132(-4)?     at [object Object]._.extend.apply (packages/ddp-server/livedata_server.js:1649:45)
I20170507-02:30:43.132(-4)?     at [object Object]._.extend.call (packages/ddp-server/livedata_server.js:1592:17)
I20170507-02:30:43.133(-4)?     at [object Object].Meteor.methods.getFullCalendarConsidered (server/googleCalendarAPI.js:186:29)
I20170507-02:30:43.133(-4)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1737:12)
I20170507-02:30:43.133(-4)?     - - - - -
I20170507-02:30:43.134(-4)?     at Request._callback (/Users/david/Desktop/meetable/node_modules/google-auth-library/lib/transporters.js:85:15)
I20170507-02:30:43.134(-4)?     at Request.self.callback (/Users/david/Desktop/meetable/node_modules/request/request.js:188:22)
I20170507-02:30:43.135(-4)?     at emitTwo (events.js:87:13)
I20170507-02:30:43.135(-4)?     at Request.emit (events.js:172:7)
I20170507-02:30:43.135(-4)?     at Request.<anonymous> (/Users/david/Desktop/meetable/node_modules/request/request.js:1171:10)
I20170507-02:30:43.135(-4)?     at emitOne (events.js:77:13)
I20170507-02:30:43.136(-4)?     at Request.emit (events.js:169:7)
I20170507-02:30:43.136(-4)?     at IncomingMessage.<anonymous> (/Users/david/Desktop/meetable/node_modules/request/request.js:1091:12)
I20170507-02:30:43.136(-4)?     at IncomingMessage.g (events.js:260:16)
I20170507-02:30:43.136(-4)?     at emitNone (events.js:72:20)
I20170507-02:30:43.387(-4)? Exception while invoking method 'updateEventsInDB' undefined
I20170507-02:31:00.452(-4)? PRETENDING TO EMAIL
I20170507-02:31:30.506(-4)? PRETENDING TO EMAIL
I20170507-02:31:30.508(-4)? PRETENDING TO EMAIL
```

**Comment by JoshuaStorm** [comment]
Have been unable to replicate->`wontfix`
